/**
  * @file ${obj.name.lower()}_dev.c
  * @author generated by mrt-device.py
  * @brief register defintions for ${obj.name} device
  * 
  */

#include "${obj.name.lower()}_dev.h"



/**
 * @brief initializes registers for device
 * @param dev ptr to ${obj.name} device
 */
void ${obj.name}_init_regs(${obj.name}_t* dev)
{
% for key,reg in obj.regs.items():
    REG_INIT( dev->${"m" + obj.camelCase(reg.name)} , ${reg.printAddr()}, ${reg.type}, REG_PERM_${reg.perm}  );
% endfor
}



% if "I2C" in obj.bus.upper():
mrt_status_t ${obj.name}_init_i2c(${obj.name}_t* dev, mrt_i2c_handle_t i2c)
{
    mrt_status_t status;

    ${obj.name}_init_regs(dev);

    status = init_i2c_register_device(dev->mRegDev, i2c, ${obj.prefix.upper()}_I2C_ADDRESS, ${obj.addrSize} );
    
    /*user-block-init-i2c*/
    /*user-block-init-i2c*/
    
    return MRT_STATUS_OK;
}
% endif
% if "SPI" in obj.bus.upper():
mrt_status_t ${obj.prefix}_init_spi(${obj.name}_t* dev, mrt_spi_handle_t spi)
{
    ${obj.name}_init_regs(dev)

    /*user-block-spi*/
    /*user-block-spi*/

    return MRT_STATUS_OK;
}
% endif

##FIELD SETTERS/GETTERS 
## % for key,reg in obj.regs.items():
## % if len(reg.fields)  > 0 :
## 
##     %for field in reg.fields:
## ${reg.type} ${obj.prefix +"_get_"+ reg.name.lower()+"_"+field.name.lower()}(${obj.name}_t* dev)
## {
##     ${reg.type} retVal;
## 
##     return retVal;
## }
## 
## mrt_status_t ${obj.prefix +"_set_"+ reg.name.lower()+"_"+field.name.lower()}(${obj.name}_t* dev, ${reg.type} val)
## {
##     return MRT_STATUS_OK;
## }
##     %endfor
## % endif
## % endfor
