/**
  * @file ${obj.name.lower()}_regs.c
  * @author generated by mrt-device.py
  * @brief register defintions for ${obj.name} device
  * 
  */

#include "Devices/RegDevice/register_device.h"

/*******************************************************************************
  Registers
*******************************************************************************/

% for key,reg in obj.regs.items():
REG_DEF( ${obj.prefix + "_" + reg.name} ,        ${reg.printAddr()},   ${reg.type},     REG_PERM_${reg.perm}  );
% endfor


/*******************************************************************************
  Flags and Values                                                                                 
*******************************************************************************/

% for key,reg in obj.regs.items():
% if (len(reg.fields) + len(reg.flags)) > 0 :
/* ${reg.name} */
    %for flag in reg.flags:
#define ${obj.prefix +"_"+reg.name+"_"+flag.name}${"\t\t\t\t\t"+reg.formatHex(flag.val)}
    %endfor
    %for field in reg.fields:
    %for val in field.vals:
#define ${obj.prefix +"_"+reg.name+"_"+field.name +"_" + val.name}${"\t\t\t\t\t"+reg.formatHex(val.val)}
    %endfor
    %endfor
% endif
% endfor
