/**
 * @file version.h
 * @author generated by mrt-version (https://github.com/uprev-mrt/mrtutils)
 * @brief version header
 * @date 10/11/22
 */

#define VERSION_MAJOR      0
#define VERSION_MINOR      0
#define VERSION_PATCH      0 
#define VERSION_BUILD      0 
#define VERSION_BRANCH     "master"
#define VERSION_COMMIT     "50d33bc825713574a07b81e38af5915753c85de1"

#define VERSION_STRING "0.0.0.0"
