#!/usr/bin/env python3
#
#@file mrt-ble
#@brief python script to generate code for gatt profile
#@author Jason Berger
#@date 03/20/2020
#



def main():
    print("As of version 0.2.5, mrt-ble has been renamed to mrt-gatt")
        


if __name__ == "__main__":
    main()